language: java
sudo: required
services:
  - docker

branches:
  - master

before_install:
  - echo TODO Setup Artifactory credentials
  - sudo apt-get update -qq

install:
  - echo TODO install debian package of CI Scripts.

script:
  - ./gradlew build
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then ./gradlew  artifactoryPublish -Partifactory_url=https://meremortal.jfrog.io/meremortal/ -Partifactory_user=${ARTIFACTORY_USER} -Partifactory_password=${ARTIFACTORY_PASS}; fi
  - |-
    docker build \
    --build-arg version="$(./gradlew -q printVersion)" \
    --build-arg war="$(./gradlew -q printWarName)" \
    -t crispy-barnacle:latest .
