language: java
sudo: required
services:
  - docker

branches:
  - master

before_install:
  - git config remote.origin.url https://${GH_TOKEN}@github.com/SwampUpMereMortals/crispy-barnacle.git
  - git config --global user.email "mere.mortal.ci@gmail.com"
  - git config --global user.name "Mere Mortal CI"
  - sudo su -c "echo -e \"deb https://${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD}@meremortal.jfrog.io/meremortal/mortal-debian precise main\n\" >> /etc/apt/sources.list"
  - sudo apt-get update -qq
  - docker login -u "${ARTIFACTORY_USER}" -p "${ARTIFACTORY_PASSWORD}" https://meremortal-mortal-docker.jfrog.io

install:
  - sudo apt-get install ci-scripts --force-yes

script:
  - set -e
  - ./gradlew build
  - export SERVICE_NAME=crispy-barnacle
  - export SERVICE_VERSION="$(./gradlew -q printVersion)"
  - export JAR_NAME="$(./gradlew -q printWarName)"
  - docker build --build-arg version=${SERVICE_VERSION} --build-arg jar=${JAR_NAME} -t meremortal-mortal-docker.jfrog.io/${SERVICE_NAME}:${SERVICE_VERSION} .
  - docker images
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      set -e;
      echo "Conducting a version bump and publish to Artifactory.";
      /opt/mere-mortals/swampup/publish-docker-image.sh ${SERVICE_NAME} ${SERVICE_VERSION};
      git clone git@github.com:SwampUpMereMortals/crispy-barnacle-deployment.git;
      cd crispy-barnacle-deployment;
      git checkout dev;
      /opt/mere-mortals/swampup/update_yaml.sh ./deployment.yaml ${SERVICE_NAME} ${SERVICE_VERSION};
      git commit -m "Update Deployment Image ${SERVICE_NAME}:${SERVICE_VERSION}" deployment.yaml;
      git push origin ${git_branch};
      cd ..;
      /opt/mere-mortals/swampup/increment-gradle-version.sh;
    fi
